<?php
// auto-generated by sfDoctrineAdmin
// date: 2008/02/27 08:42:00
?>

<style type="text/css">
#lightbox{
    position: absolute;
    top:50%;
    left:50%;
    z-index:9999;
    width:500px;
    height:400px;
    margin:-220px 0 0 -250px;
    overflow: scroll;
    background-color: #fff;
    }
#lightbox fieldset { width: 450px; }
#lightbox[id]{ /* IE6 and below Can't See This */
    position:fixed;
    }
    
#overlay{
    position: absolute;
    top:0;
    left:0;
    width:100%;
    height:100%;
    z-index:5000;   
    background-color:#000;
    -moz-opacity: 0.8;
    opacity:.80;
    filter: alpha(opacity=80);
    }
#overlay[id]{ /* IE6 and below Can't See This */
    position:fixed;
    }    

</style>

<?php echo form_tag('sfUserUser/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($sf_user_user, 'getid') ?>

<fieldset id="sf_fieldset_details" class="">
<h2><?php echo __('Details') ?></h2>

<div class="form-row">
  <?php echo label_for('sf_user_user[prefix]', __($labels['sf_user_user{prefix}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_user{prefix}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_user{prefix}')): ?>
    <?php echo form_error('sf_user_user{prefix}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'prefix',
  ),
), array (
  'size' => 20,
  'control_name' => 'sf_user_user[prefix]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_user[first_name]', __($labels['sf_user_user{first_name}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_user{first_name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_user{first_name}')): ?>
    <?php echo form_error('sf_user_user{first_name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'first_name',
  ),
), array (
  'size' => 20,
  'control_name' => 'sf_user_user[first_name]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_user[middle_name]', __($labels['sf_user_user{middle_name}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_user{middle_name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_user{middle_name}')): ?>
    <?php echo form_error('sf_user_user{middle_name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'middle_name',
  ),
), array (
  'size' => 20,
  'control_name' => 'sf_user_user[middle_name]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_user[last_name]', __($labels['sf_user_user{last_name}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_user{last_name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_user{last_name}')): ?>
    <?php echo form_error('sf_user_user{last_name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'last_name',
  ),
), array (
  'size' => 20,
  'control_name' => 'sf_user_user[last_name]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_user[suffix]', __($labels['sf_user_user{suffix}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_user{suffix}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_user{suffix}')): ?>
    <?php echo form_error('sf_user_user{suffix}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'suffix',
  ),
), array (
  'size' => 20,
  'control_name' => 'sf_user_user[suffix]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_user[company]', __($labels['sf_user_user{company}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_user{company}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_user{company}')): ?>
    <?php echo form_error('sf_user_user{company}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'company',
  ),
), array (
  'size' => 45,
  'control_name' => 'sf_user_user[company]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_user[date_of_birth]', __($labels['sf_user_user{date_of_birth}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_user{date_of_birth}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_user{date_of_birth}')): ?>
    <?php echo form_error('sf_user_user{date_of_birth}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($sf_user_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'date_of_birth',
  ),
), array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'sf_user_user[date_of_birth]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<div id="sf_guard_update"></div>
<fieldset id="sfGuardUser" class="sf_fieldset_details">
<?php include_partial('sfGuardUser/ajaxList', array('sf_user_user' => $sf_user_user)); ?>
</fieldset>

<div id="addresses_update"></div>
<fieldset id="sfUserAddress" class="sf_fieldset_details">
<?php include_partial('sfUserAddress/ajaxList', array('sf_user_user' => $sf_user_user)); ?>
</fieldset>

<div id="phones_update"></div>
<fieldset id="sfUserPhone" class="sf_fieldset_details">
<?php include_partial('sfUserPhone/ajaxList', array('sf_user_user' => $sf_user_user)); ?>
</fieldset>

<div id="email_addresses_update"></div>
<fieldset id="sfUserEmailAddress" class="sf_fieldset_details">
<?php include_partial('sfUserEmailAddress/ajaxList', array('sf_user_user' => $sf_user_user)); ?>
</fieldset>

<div id="im_accounts_update"></div>
<fieldset id="sfUserImAccount" class="sf_fieldset_details">
<?php include_partial('sfUserImAccount/ajaxList', array('sf_user_user' => $sf_user_user)); ?>
</fieldset>

<div id="im_billings_update"></div>
<fieldset id="sfUserBilling" class="sf_fieldset_details">
<?php include_partial('sfUserBilling/ajaxList', array('sf_user_user' => $sf_user_user)); ?>
</fieldset>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('sf_user_user[updated_at]', __($labels['sf_user_user{updated_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_user{updated_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_user{updated_at}')): ?>
    <?php echo form_error('sf_user_user{updated_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_user_user->get('updated_at') !== null && $sf_user_user->get('updated_at') !== '') ? format_date($sf_user_user->get('updated_at'), "MM/dd/yy hh:mm a") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_user[UpdatedBy]', __($labels['sf_user_user{UpdatedBy}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_user{UpdatedBy}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_user{UpdatedBy}')): ?>
    <?php echo form_error('sf_user_user{UpdatedBy}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = $sf_user_user->get('UpdatedBy'); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_user[created_at]', __($labels['sf_user_user{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_user{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_user{created_at}')): ?>
    <?php echo form_error('sf_user_user{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_user_user->get('created_at') !== null && $sf_user_user->get('created_at') !== '') ? format_date($sf_user_user->get('created_at'), "MM/dd/yy hh:mm a") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_user[CreatedBy]', __($labels['sf_user_user{CreatedBy}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_user{CreatedBy}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_user{CreatedBy}')): ?>
    <?php echo form_error('sf_user_user{CreatedBy}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = $sf_user_user->get('CreatedBy'); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('sf_user_user' => $sf_user_user)) ?>

</form>

<div id="overlay" style="display: none;"></div>
<div id="lightbox" style="display: none;">  
</div>

<ul class="sf_admin_actions">
      <?php if ($sf_user->hasCredential('-')): ?>
<li class="float-left"><?php if ($sf_user_user->get('id')): ?>
<?php echo button_to(__('delete'), 'sfUserUser/delete?id='.$sf_user_user->get('id'), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>

<?php endif; ?>  </ul>
