<?php
// auto-generated by sfDoctrineAdmin
// date: 2008/02/27 09:16:35
?>
<?php use_helper('Javascript', 'Form') ?>
<?php echo form_remote_tag(array(
    'complete'   => "$('overlay', 'lightbox').invoke('hide')",
    'update'   => "sfUserAddress",
    'url'      => 'sfUserAddress/ajaxSave',
), array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($sf_user_address, 'getid') ?>
<?php echo input_hidden_tag('sf_user_address[User]', $sf_user_address['user_id']) ?>

<fieldset id="sf_fieldset_details" class="">
<h2><?php echo __('Details') ?></h2>

<div class="form-row">
  <?php echo label_for('sf_user_address[rank]', __($labels['sf_user_address{rank}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_address{rank}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_address{rank}')): ?>
    <?php echo form_error('sf_user_address{rank}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_address, array (
  0 => 'get',
  1 => 
  array (
    0 => 'rank',
  ),
), array (
  'size' => 7,
  'control_name' => 'sf_user_address[rank]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_address[AddressType]', __($labels['sf_user_address{AddressType}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_address{AddressType}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_address{AddressType}')): ?>
    <?php echo form_error('sf_user_address{AddressType}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($sf_user_address, array (
  0 => 'get',
  1 => 
  array (
    0 => 'address_type_id',
  ),
), array (
  'related_class' => 'sfUserAddressType',
  'control_name' => 'sf_user_address[AddressType]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_address[address1]', __($labels['sf_user_address{address1}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_address{address1}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_address{address1}')): ?>
    <?php echo form_error('sf_user_address{address1}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_address, array (
  0 => 'get',
  1 => 
  array (
    0 => 'address1',
  ),
), array (
  'size' => 45,
  'control_name' => 'sf_user_address[address1]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_address[address2]', __($labels['sf_user_address{address2}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_address{address2}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_address{address2}')): ?>
    <?php echo form_error('sf_user_address{address2}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_address, array (
  0 => 'get',
  1 => 
  array (
    0 => 'address2',
  ),
), array (
  'size' => 45,
  'control_name' => 'sf_user_address[address2]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_address[address3]', __($labels['sf_user_address{address3}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_address{address3}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_address{address3}')): ?>
    <?php echo form_error('sf_user_address{address3}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_address, array (
  0 => 'get',
  1 => 
  array (
    0 => 'address3',
  ),
), array (
  'size' => 45,
  'control_name' => 'sf_user_address[address3]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_address[city]', __($labels['sf_user_address{city}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_address{city}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_address{city}')): ?>
    <?php echo form_error('sf_user_address{city}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_address, array (
  0 => 'get',
  1 => 
  array (
    0 => 'city',
  ),
), array (
  'size' => 45,
  'control_name' => 'sf_user_address[city]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_address[State]', __($labels['sf_user_address{State}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_address{State}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_address{State}')): ?>
    <?php echo form_error('sf_user_address{State}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($sf_user_address, array (
  0 => 'get',
  1 => 
  array (
    0 => 'state_id',
  ),
), array (
  'related_class' => 'sfUserState',
  'control_name' => 'sf_user_address[State]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_address[zip]', __($labels['sf_user_address{zip}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_address{zip}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_address{zip}')): ?>
    <?php echo form_error('sf_user_address{zip}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_address, array (
  0 => 'get',
  1 => 
  array (
    0 => 'zip',
  ),
), array (
  'size' => 20,
  'control_name' => 'sf_user_address[zip]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('sf_user_address[updated_at]', __($labels['sf_user_address{updated_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_address{updated_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_address{updated_at}')): ?>
    <?php echo form_error('sf_user_address{updated_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_user_address->get('updated_at') !== null && $sf_user_address->get('updated_at') !== '') ? format_date($sf_user_address->get('updated_at'), "MM/dd/yy hh:mm a") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_address[UpdatedBy]', __($labels['sf_user_address{UpdatedBy}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_address{UpdatedBy}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_address{UpdatedBy}')): ?>
    <?php echo form_error('sf_user_address{UpdatedBy}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = $sf_user_address->get('UpdatedBy'); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_address[created_at]', __($labels['sf_user_address{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_address{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_address{created_at}')): ?>
    <?php echo form_error('sf_user_address{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_user_address->get('created_at') !== null && $sf_user_address->get('created_at') !== '') ? format_date($sf_user_address->get('created_at'), "MM/dd/yy hh:mm a") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_address[CreatedBy]', __($labels['sf_user_address{CreatedBy}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_address{CreatedBy}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_address{CreatedBy}')): ?>
    <?php echo form_error('sf_user_address{CreatedBy}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = $sf_user_address->get('CreatedBy'); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('ajax_edit_actions', array('sf_user_address' => $sf_user_address)) ?>

</form>