<?php
// auto-generated by sfDoctrineAdmin
// date: 2008/02/27 09:16:35
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Editing Address For "%%User%%"', 
array('%%User%%' => $sf_user_address->get('User'))) ?></h1>

<div id="sf_admin_header">
<?php include_partial('sfUserAddress/edit_header', array('sf_user_address' => $sf_user_address)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('sfUserAddress/edit_messages', array('sf_user_address' => $sf_user_address, 'labels' => $labels)) ?>
<?php include_partial('sfUserAddress/ajax_edit_form', array('sf_user_address' => $sf_user_address, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('sfUserAddress/edit_footer', array('sf_user_address' => $sf_user_address)) ?>
</div>

</div>
