<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfUserPhone extends BasesfUserPhone
{

  /**
   * This returns a formatted phone number based on length of number
   *
   * @return string
   */
  public function __toString()
  {
    $stripped_phone = preg_replace('/[^\d]/', '', $this['number']);
    switch ( strlen($stripped_phone) )
    {
      default: //default is 10 (xxx) xxx-xxx 
        $formatted_phone = preg_replace('/(\d{3})(\d{3})(\d{4})/', "($1) $2-$3", $stripped_phone);
        break; 
    }
    return $formatted_phone . ( ( strlen($this['extension']) ) ? " x {$this['extension']}" : '' );
  }
  
  public function getIsPrimary()
  {
    return ( $this['rank'] == 1 );
  }
  
  public function makePrimary()
  {
    
  }
  

}