<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfUserBilling extends BasesfUserBilling
{


  public function getDecrytedCreditCardNumber()
  {
    return $this->rawGet('credit_card_number');
  }

  public function getFullCreditCardNumber()
  {
    return $this->getDecrytedCreditCardNumber();
  }

  public function getCreditCardNumber()
  {
    if ( ! $this->getFullCreditCardNumber() )
      return '';
    return 'XXXXXXXXXXXXX' . substr($this->getFullCreditCardNumber(), -4);;
  }

  public function setCreditCardNumber($credit_card_number)
  {
    if( strstr($credit_card_number, 'XXXX')) return false;

    parent::_set('credit_card_number', $credit_card_number);

  }

  public function getCreditCardExpirationDate()
  {
    return $this['credit_card_exp_month'] . '/' . $this['credit_card_exp_year'];
  }

  public function __toString()
  {
    if ( $this['method'] == 'CREDIT' )
      return
        ( strlen($this['name']) ? "{$this['name']}<br />" : "" )
        . ( strlen($this['credit_card_number']) ? "{$this['credit_card_number']}<br />" : "" )
        . ( strlen($this['address1']) ? "{$this['address1']}<br />" : "" )
        . ( strlen($this['address2']) ? "{$this['address2']}<br />" : "" )
        . "{$this['city']}, {$this['state']} {$this['zip']}"
        ;
    else
      return
        ( strlen($this['name']) ? "{$this['name']}<br />" : "" )
        . ( strlen($this['check_number']) ? "Check #: {$this['check_number']}<br />" : "" )
        . ( strlen($this['check_routing_number']) ? "{$this['check_routing_number']}" : "" )
        . ( strlen($this['check_account_number']) ? "{$this['check_account_number']}<br />" : "<br />" )
        . ( strlen($this['check_bank_name']) ? "{$this['check_bank_name']}" : "" )
        . ( strlen($this['check_branch_state']) ? " ({$this['check_branch_state']})<br />" : "" )
        . ( strlen($this['address1']) ? "{$this['address1']}<br />" : "" )
        . ( strlen($this['address2']) ? "{$this['address2']}<br />" : "" )
        . "{$this['city']}, {$this['state']} {$this['zip']}"
        ;

  }

  public function getIsPrimary()
  {
    return ( $this['rank'] == 1 );
  }

  public function makePrimary()
  {

  }

}
