<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfUserImAccount extends BasesfUserImAccount
{
  
  public function getIsPrimary()
  {
    return ( $this['rank'] == 1 );
  }
  
  public function makePrimary()
  {
    
  }
  
  public function __toString()
  {
    return $this['ImAccountType'] . ": " . $this['nickname'];
  }

}