<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfUserAddress extends BasesfUserAddress
{

  public function __toString()
  {
    return 
      ( strlen($this['address1']) ? "{$this['address1']}<br />" : "Blh" )
      . ( strlen($this['address2']) ? "{$this['address2']}<br />" : "" )
      . ( strlen($this['address3']) ? "{$this['address3']}<br />" : "" )
      . "{$this['city']}, {$this['State']} {$this['zip']}"
    ;
    
  }

  public function getIsPrimary()
  {
    return ( $this['rank'] == 1 );
  }
  
  public function makePrimary()
  {
    
  }

}