<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfUserState extends BasesfUserState
{

  public function __toString()
  {
    return ucwords(strtolower($this->name));
  }

}