<?php
// auto-generated by sfDoctrineAdmin
// date: 2008/03/28 14:59:23
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Editing Billing For "%%User%%"', 
array('%%User%%' => $sf_user_billing->User)) ?></h1>

<div id="sf_admin_header">
<?php include_partial('sfUserBilling/edit_header', array('sf_user_billing' => $sf_user_billing)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('sfUserBilling/edit_messages', array('sf_user_billing' => $sf_user_billing, 'labels' => $labels)) ?>
<?php include_partial('sfUserBilling/ajax_edit_form', array('sf_user_billing' => $sf_user_billing, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('sfUserBilling/edit_footer', array('sf_user_billing' => $sf_user_billing)) ?>
</div>

</div>
