<?php
// auto-generated by sfDoctrineAdmin
// date: 2008/03/28 13:46:41
?>
<?php use_helper('Javascript', 'Form') ?>
<?php echo form_remote_tag(array(
    'complete'   => "$('overlay', 'lightbox').invoke('hide')",
    'update'   => "sfUserPhone",
    'url'      => 'sfUserPhone/ajaxSave',
), array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($sf_user_phone, 'getid') ?>
<?php echo input_hidden_tag('sf_user_phone[User]', $sf_user_phone['user_id']) ?>

<fieldset id="sf_fieldset_details" class="">
<h2><?php echo __('Details') ?></h2>

<div class="form-row">
  <?php echo label_for('sf_user_phone[PhoneType]', __($labels['sf_user_phone{PhoneType}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_phone{PhoneType}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_phone{PhoneType}')): ?>
    <?php echo form_error('sf_user_phone{PhoneType}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($sf_user_phone, array (
  0 => 'get',
  1 => 
  array (
    0 => 'phone_type_id',
  ),
), array (
  'related_class' => 'sfUserPhoneType',
  'control_name' => 'sf_user_phone[PhoneType]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_phone[rank]', __($labels['sf_user_phone{rank}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_phone{rank}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_phone{rank}')): ?>
    <?php echo form_error('sf_user_phone{rank}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_phone, array (
  0 => 'get',
  1 => 
  array (
    0 => 'rank',
  ),
), array (
  'size' => 7,
  'control_name' => 'sf_user_phone[rank]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_phone[number]', __($labels['sf_user_phone{number}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_phone{number}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_phone{number}')): ?>
    <?php echo form_error('sf_user_phone{number}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_phone, array (
  0 => 'get',
  1 => 
  array (
    0 => 'number',
  ),
), array (
  'size' => 20,
  'control_name' => 'sf_user_phone[number]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_phone[extension]', __($labels['sf_user_phone{extension}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_phone{extension}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_phone{extension}')): ?>
    <?php echo form_error('sf_user_phone{extension}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_phone, array (
  0 => 'get',
  1 => 
  array (
    0 => 'extension',
  ),
), array (
  'size' => 20,
  'control_name' => 'sf_user_phone[extension]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('sf_user_phone[updated_at]', __($labels['sf_user_phone{updated_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_phone{updated_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_phone{updated_at}')): ?>
    <?php echo form_error('sf_user_phone{updated_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_user_phone->updated_at !== null && $sf_user_phone->updated_at !== '') ? format_date($sf_user_phone->updated_at, "MM/dd/yy hh:mm a") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_phone[UpdatedBy]', __($labels['sf_user_phone{UpdatedBy}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_phone{UpdatedBy}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_phone{UpdatedBy}')): ?>
    <?php echo form_error('sf_user_phone{UpdatedBy}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = $sf_user_phone->UpdatedBy; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_phone[created_at]', __($labels['sf_user_phone{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_phone{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_phone{created_at}')): ?>
    <?php echo form_error('sf_user_phone{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_user_phone->created_at !== null && $sf_user_phone->created_at !== '') ? format_date($sf_user_phone->created_at, "MM/dd/yy hh:mm a") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_phone[CreatedBy]', __($labels['sf_user_phone{CreatedBy}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_phone{CreatedBy}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_phone{CreatedBy}')): ?>
    <?php echo form_error('sf_user_phone{CreatedBy}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = $sf_user_phone->CreatedBy; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('ajax_edit_actions', array('sf_user_phone' => $sf_user_phone)) ?>

</form>