<?php
// auto-generated by sfDoctrineAdmin
// date: 2008/03/28 13:46:41
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Editing Phone for User "%%User%%"', 
array('%%User%%' => $sf_user_phone->User)) ?></h1>

<div id="sf_admin_header">
<?php include_partial('sfUserPhone/edit_header', array('sf_user_phone' => $sf_user_phone)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('sfUserPhone/edit_messages', array('sf_user_phone' => $sf_user_phone, 'labels' => $labels)) ?>
<?php include_partial('sfUserPhone/ajax_edit_form', array('sf_user_phone' => $sf_user_phone, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('sfUserPhone/edit_footer', array('sf_user_phone' => $sf_user_phone)) ?>
</div>

</div>
