<?php
// auto-generated by sfDoctrineAdmin
// date: 2008/03/29 00:12:56
?>

<?php use_helper('Javascript', 'Form') ?>
<?php echo form_remote_tag(array(
    'complete'   => "$('overlay', 'lightbox').invoke('hide')",
    'update'   => "sfGuardUser",
    'url'      => 'sfGuardUser/ajaxSave',
), array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($sf_guard_user, 'getid') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('sf_guard_user[username]', __($labels['sf_guard_user{username}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{username}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{username}')): ?>
    <?php echo form_error('sf_guard_user{username}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_guard_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'username',
  ),
), array (
  'control_name' => 'sf_guard_user[username]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[password]', __($labels['sf_guard_user{password}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{password}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{password}')): ?>
    <?php echo form_error('sf_guard_user{password}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('password', array('type' => 'edit', 'sf_guard_user' => $sf_guard_user)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[password_bis]', __($labels['sf_guard_user{password_bis}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{password_bis}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{password_bis}')): ?>
    <?php echo form_error('sf_guard_user{password_bis}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('password_bis', array('type' => 'edit', 'sf_guard_user' => $sf_guard_user)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_information" class="">
<h2><?php echo __('Information') ?></h2>


<div class="form-row">
  <?php echo label_for('sf_guard_user[last_login]', __($labels['sf_guard_user{last_login}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{last_login}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{last_login}')): ?>
    <?php echo form_error('sf_guard_user{last_login}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_guard_user->last_login !== null && $sf_guard_user->last_login !== '') ? format_date($sf_guard_user->last_login, "f") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[created_at]', __($labels['sf_guard_user{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{created_at}')): ?>
    <?php echo form_error('sf_guard_user{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_guard_user->created_at !== null && $sf_guard_user->created_at !== '') ? format_date($sf_guard_user->created_at, "f") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[updated_at]', __($labels['sf_guard_user{updated_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{updated_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{updated_at}')): ?>
    <?php echo form_error('sf_guard_user{updated_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_guard_user->updated_at !== null && $sf_guard_user->updated_at !== '') ? format_date($sf_guard_user->updated_at, "f") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_permissions_and_groups" class="">
<h2><?php echo __('Permissions and Groups') ?></h2>


<div class="form-row">
  <?php echo label_for('sf_guard_user[is_active]', __($labels['sf_guard_user{is_active}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{is_active}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{is_active}')): ?>
    <?php echo form_error('sf_guard_user{is_active}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($sf_guard_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'is_active',
  ),
), array (
  'control_name' => 'sf_guard_user[is_active]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[groups]', __($labels['sf_guard_user{groups}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{groups}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{groups}')): ?>
    <?php echo form_error('sf_guard_user{groups}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_doctrine_admin_check_list($sf_guard_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'groups',
  ),
), array (
  'control_name' => 'sf_guard_user[groups]',
  'associated_label' => 'Assigned',
  'unassociated_label' => 'Available',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_guard_user[permissions]', __($labels['sf_guard_user{permissions}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_guard_user{permissions}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_guard_user{permissions}')): ?>
    <?php echo form_error('sf_guard_user{permissions}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_doctrine_admin_check_list($sf_guard_user, array (
  0 => 'get',
  1 => 
  array (
    0 => 'permissions',
  ),
), array (
  'control_name' => 'sf_guard_user[permissions]',
  'associated_label' => 'Assigned',
  'unassociated_label' => 'Available',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('ajax_edit_actions', array('sf_guard_user' => $sf_guard_user)) ?>

</form>