generator:
  class:              sfDoctrineAdminGenerator
  param:
    model_class:      sfUserImAccount
    theme:            default
      
    fields:
      updated_at: { type: plain, params: date_format='MM/dd/yy hh:mm a' }
      UpdatedBy: { type: plain }
      created_at: { type: plain, params: date_format='MM/dd/yy hh:mm a' }
      CreatedBy: { type: plain }
      
    list:
      title: Instant Messaging Accounts for Users
      display: [ User, rank, ImAccountType, nickname ]
      object_actions:
        _edit:    -
        _delete:  -
      actions:
        _create:  { name: Add Instant Messaging Account }
      sort_by:    [ sfUserUser, asc ]

    edit:
      title: Editing Instant Messaging Account for User "%%User%%"
      display:
        "Details": [_User,  ImAccountType, rank, nickname ]
        "NONE": [ updated_at, UpdatedBy, created_at, CreatedBy ]
      fields:
      actions:
          _save: -
          _save_and_add: -
          _save_and_list: -
          _list: -
          _delete: -
