<?php
// auto-generated by sfDoctrineAdmin
// date: 2008/03/28 16:36:49
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Editing Instant Messaging Account for User "%%User%%"', 
array('%%User%%' => $sf_user_im_account->User)) ?></h1>

<div id="sf_admin_header">
<?php include_partial('sfUserImAccount/edit_header', array('sf_user_im_account' => $sf_user_im_account)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('sfUserImAccount/edit_messages', array('sf_user_im_account' => $sf_user_im_account, 'labels' => $labels)) ?>
<?php include_partial('sfUserImAccount/ajax_edit_form', array('sf_user_im_account' => $sf_user_im_account, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('sfUserImAccount/edit_footer', array('sf_user_im_account' => $sf_user_im_account)) ?>
</div>

</div>
