<?php
// auto-generated by sfDoctrineAdmin
// date: 2008/03/26 18:54:23
?>

<?php use_helper('Javascript', 'Form') ?>
<?php echo form_remote_tag(array(
    'complete'   => "$('overlay', 'lightbox').invoke('hide')",
    'update'   => "sfUserEmailAddress",
    'url'      => 'sfUserEmailAddress/ajaxSave',
), array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($sf_user_email_address, 'getid') ?>
<?php echo input_hidden_tag('sf_user_email_address[User]', $sf_user_email_address['user_id']) ?>


<fieldset id="sf_fieldset_details" class="">
<h2><?php echo __('Details') ?></h2>

<div class="form-row">
  <?php echo label_for('sf_user_email_address[rank]', __($labels['sf_user_email_address{rank}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_email_address{rank}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_email_address{rank}')): ?>
    <?php echo form_error('sf_user_email_address{rank}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_email_address, array (
  0 => 'get',
  1 => 
  array (
    0 => 'rank',
  ),
), array (
  'size' => 7,
  'control_name' => 'sf_user_email_address[rank]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_email_address[address]', __($labels['sf_user_email_address{address}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_email_address{address}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_email_address{address}')): ?>
    <?php echo form_error('sf_user_email_address{address}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($sf_user_email_address, array (
  0 => 'get',
  1 => 
  array (
    0 => 'address',
  ),
), array (
  'size' => 80,
  'control_name' => 'sf_user_email_address[address]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('sf_user_email_address[updated_at]', __($labels['sf_user_email_address{updated_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_email_address{updated_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_email_address{updated_at}')): ?>
    <?php echo form_error('sf_user_email_address{updated_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_user_email_address->updated_at !== null && $sf_user_email_address->updated_at !== '') ? format_date($sf_user_email_address->updated_at, "MM/dd/yy hh:mm a") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_email_address[UpdatedBy]', __($labels['sf_user_email_address{UpdatedBy}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_email_address{UpdatedBy}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_email_address{UpdatedBy}')): ?>
    <?php echo form_error('sf_user_email_address{UpdatedBy}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = $sf_user_email_address->UpdatedBy; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_email_address[created_at]', __($labels['sf_user_email_address{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_email_address{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_email_address{created_at}')): ?>
    <?php echo form_error('sf_user_email_address{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = ($sf_user_email_address->created_at !== null && $sf_user_email_address->created_at !== '') ? format_date($sf_user_email_address->created_at, "MM/dd/yy hh:mm a") : ''; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('sf_user_email_address[CreatedBy]', __($labels['sf_user_email_address{CreatedBy}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('sf_user_email_address{CreatedBy}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('sf_user_email_address{CreatedBy}')): ?>
    <?php echo form_error('sf_user_email_address{CreatedBy}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = $sf_user_email_address->CreatedBy; echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('ajax_edit_actions', array('sf_user_email_address' => $sf_user_email_address)) ?>

</form>