<?php
// auto-generated by sfDoctrineAdmin
// date: 2008/03/26 18:54:23
?>
<ul class="sf_admin_actions">
    <li><?php echo submit_tag(__('save'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
    <li><?php echo button_to_function(__('cancel'), "$('overlay', 'lightbox').invoke('hide')", array (
  'name' => 'cancel',
  'class' => 'sf_admin_action_cancel',
)) ?></li>
</ul>
